<footer> <!--footer fdr bottom of the page-->
        <div class="footer-container">
            <div class="footer-logo"> <!--image for the logo-->
                <img src="images/logo.png" alt="Team Logo">
            </div>
            <div class="footer-copyright"> <!--Copywright text-->
                <p>© 2025 Team Anonymous</p>
            </div>
            <nav class="footer-nav"> <!--Privacy link-->
                <a href="privacy.html">Privacy</a>
            </nav>
        </div>
    </footer>